# This is the default configuration for DonationPoints.
# Change any information you wish unless documented otherwise not to do so.
General:
  LogTransactions: true
  AutoCheckForUpdates: true
#MySQL Login Information. After you put the info in, restart your server.
#You'll get a confirmation message if you can successfully connect.
MySQL:
  host: localhost
  port: 3306
  username: root
  password: 
  database: minecraft
packages:
  # These are the 'default' packages. PLEASE change these.
  # Use '%player' where you would like the player's name to go.
  # You can run as many commands as you wish.
  # Please make sure no field below is blank.
  God:
    price: 500
    description: This will give you god mode.
    commands:
    - god %player
    - say %player has received god mode.
  kick:
    price: 1000
    description: This will kick the player.
    commands:
    - kick %player