# This is the default configuration for DonationPoints.
# Change any information you wish unless documented otherwise not to do so.
General:
  #This is the version of the config the plugin is using. Please do not change this. This is to check for any updates your config may need.
  config: 1.0
MySQL:
  host: localhost
  port: 3306
  username: root
  password: 
  database: minecraft
packages:
  # These are the 'default' packages. PLEASE change these.
  # Use '%player' where you would like the player's name to go.
  # You can run as many commands as you wish.
  # Please make sure no field below is blank.
  God:
    price: 500
    description: This will give you god mode.
    commands:
    - god %player
    - say %player has received god mode.
  kick:
    price: 1000
    description: This will kick the player.
    commands:
    - kick %player