name: DonationPoints
author: MistPhizzle
version: 1.3-DEV
main: com.mistphizzle.donationpoints.plugin.DonationPoints
commands:
  donationpoints:
    usage: /<command>
    aliases: [dp, points]
permissions:
  donationpoints.admin:
    default: op
    children:
      donationpoints.sign.create: true
      donationpoints.sign.use: true
      donationpoints.create: true
      donationpoints.create.others: true
      donationpoints.balance: true
      donationpoints.balance.others: true
      donationpoints.give: true
      donationpoints.take: true
      donationpoints.set: true
      donationpoints.update: true
      donationpoints.reload: true
      donationpoints.version: true
  donationpoints.user:
    default: op
    children:
      donationpoints.sign.use: true
      donationpoints.create: true
      donationpoints.balance: true
      donationpoints.confirm: true
      donationpoints.package.info: true