General:
  AutoCreateAccounts: true
  SignMessage: Premium
  Transferrable: false
MySQL:
  engine: sqlite
  SQLiteDB: donationpoints.db
  host: localhost
  port: 3306
  username: root
  password: 
  database: minecraft
packages:
  God:
    price: 500
    description: This will give you god mode.
    haslimit: true
    limit: 3
    activateimmediately: false
    expires: true
    expiretime: 1
    commands:
    - god %player
    - say %player has received god mode.
    expirecommands:
    - god %player
    - say %player -- Your god mode has expired.
  kick:
    price: 1000
    description: This will kick the player.
    haslimit: false
    limit: 1
    activateimmediately: true
    expires: false
    expiretime: 1
    commands:
    - kick %player
    expirecommands:
    - say %player -- Your kick as expired.