General:
  AutoCreateAccounts:
  SignMessage: 
  Transferrable: 
  ExpireOnStartup:
  AutoFillSigns:
  SpecificPermissions:
  PurgeEmptyAccountsOnStartup:
  ConfigVersion: 
MySQL:
  engine:
  SQLiteDB:
  host:
  port:
  username:
  password: 
  database:
  TransactionTable:
  PlayerTable:
messages:
  Prefix:
  NoPermission:
  InvalidArguments:
  PlayerOnly:
  ReloadSuccessful:
  NoCommandExists:
  DPConfirm:
  DPActivate:
  DPSuccessfulActivation:
  DPFailedActivation:
  ExpireDate:
  DPGive:
  DPTake:
  DPSet:
  NoAccount:
  AccountCreated:
  AccountAlreadyExists:
  NoTransfer:
  TransferOff:
  TransferSent:
  TransferReceive:
  PlayerBalance:
  OtherBalance:
  NoPurchaseStarted:
  PurchaseSuccessful:
  NeedActivation:
  LimitReached:
  PackageActivated:
  InvalidPackage:
  NotEnoughPoints:
  DPPrerequisite:
packages: